language: node_js

node_js:
  - "4.1"
  - "4.0"

before_script:
    - npm install -g gulp    
    - npm install -g mocha
    - npm install -g babel

script: mocha --recursive --compilers js:babel/register
